sudo: false
dist: xenial
language: generic
services: docker

env:
  global:
    - IMAGE_NAME=django-mobans-empty-image:this

before_script:
  - docker run -v=$(pwd):/app --workdir=/app djangomobans/lint-image

script:
  - hooks/build
  - docker images

notifications:
  email: false
